
#pragma once
// Stub of iddcx.h at IDDCX_VERSION_MINOR semantics (structures shaped per
// Microsoft's public documentation).
#include "windows.h"
#include "wdf.h"
struct IDDCX_ADAPTER__; typedef IDDCX_ADAPTER__* IDDCX_ADAPTER;
struct IDDCX_MONITOR__; typedef IDDCX_MONITOR__* IDDCX_MONITOR;
struct IDDCX_SWAPCHAIN__; typedef IDDCX_SWAPCHAIN__* IDDCX_SWAPCHAIN;
// WdfObjectGet_* also accept IddCx handles (they are WDF objects).
#define WDF_DECLARE_CONTEXT_TYPE_IDDCX(T) 
enum IDDCX_FEATURE_IMPLEMENTATION { IDDCX_FEATURE_IMPLEMENTATION_NONE = 0 };
enum IDDCX_TRANSMISSION_TYPE { IDDCX_TRANSMISSION_TYPE_WIRED_OTHER = 8 };
enum IDDCX_MONITOR_DESCRIPTION_TYPE { IDDCX_MONITOR_DESCRIPTION_TYPE_EDID = 1 };
enum IDDCX_MONITOR_MODE_ORIGIN { IDDCX_MONITOR_MODE_ORIGIN_MONITORDESCRIPTOR = 1, IDDCX_MONITOR_MODE_ORIGIN_DRIVER = 2 };
enum IDDCX_PATH_FLAGS { IDDCX_PATH_FLAGS_NONE=0, IDDCX_PATH_FLAGS_ACTIVE = 1, IDDCX_PATH_FLAGS_CHANGED = 2 };
enum DISPLAYCONFIG_SCANLINE_ORDERING { DISPLAYCONFIG_SCANLINE_ORDERING_PROGRESSIVE = 1 };
enum DISPLAYCONFIG_OUTPUT_TECHNOLOGY { DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL = 10, DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HDMI = 5 };
struct DISPLAYCONFIG_RATIONAL { UINT32 Numerator; UINT32 Denominator; };
struct DISPLAYCONFIG_2DREGION { UINT32 cx; UINT32 cy; };
struct DISPLAYCONFIG_VIDEO_SIGNAL_INFO {
  UINT64 pixelRate; DISPLAYCONFIG_RATIONAL hSyncFreq; DISPLAYCONFIG_RATIONAL vSyncFreq;
  struct SIZEL { LONG cx; LONG cy; }; SIZEL activeSize; SIZEL totalSize;
  struct { UINT32 videoStandard; UINT32 vSyncFreqDivider; } AdditionalSignalInfo;
  DISPLAYCONFIG_SCANLINE_ORDERING scanLineOrdering;
};
struct DISPLAYCONFIG_TARGET_MODE { DISPLAYCONFIG_VIDEO_SIGNAL_INFO targetVideoSignalInfo; };
struct IDDCX_ENDPOINT_VERSION { UINT Size; UINT MajorVer; UINT MinorVer; UINT Build; UINT64 SKU; };
struct IDDCX_ENDPOINT_DIAGNOSTIC_INFO {
  UINT Size; const WCHAR* pEndPointFriendlyName; const WCHAR* pEndPointManufacturerName;
  const WCHAR* pEndPointModelName; IDDCX_ENDPOINT_VERSION* pFirmwareVersion; IDDCX_ENDPOINT_VERSION* pHardwareVersion;
  IDDCX_FEATURE_IMPLEMENTATION GammaSupport; IDDCX_TRANSMISSION_TYPE TransmissionType;
};
enum IDDCX_ADAPTER_FLAGS { IDDCX_ADAPTER_FLAGS_NONE = 0 };
struct IDDCX_ADAPTER_CAPS {
  UINT Size; IDDCX_ADAPTER_FLAGS Flags; UINT64 MaxDisplayPipelineRate; UINT MaxMonitorsSupported;
  IDDCX_ENDPOINT_DIAGNOSTIC_INFO EndPointDiagnostics; UINT StaticDesktopReencodeFrameCount;
};
struct IDDCX_MONITOR_DESCRIPTION { UINT Size; IDDCX_MONITOR_DESCRIPTION_TYPE Type; UINT DataSize; void* pData; };
struct IDDCX_MONITOR_INFO {
  UINT Size; DISPLAYCONFIG_OUTPUT_TECHNOLOGY MonitorType; UINT ConnectorIndex;
  IDDCX_MONITOR_DESCRIPTION MonitorDescription; GUID MonitorContainerId;
};
struct IDDCX_MONITOR_MODE { UINT Size; IDDCX_MONITOR_MODE_ORIGIN Origin; DISPLAYCONFIG_VIDEO_SIGNAL_INFO MonitorVideoSignalInfo; };
struct IDDCX_TARGET_MODE { UINT Size; DISPLAYCONFIG_TARGET_MODE TargetVideoSignalInfo; };
struct IDDCX_PATH { UINT Size; IDDCX_MONITOR MonitorObject; UINT Flags; DISPLAYCONFIG_VIDEO_SIGNAL_INFO TargetVideoSignalInfo; };
struct IDARG_IN_ADAPTER_INIT { WDFDEVICE WdfDevice; IDDCX_ADAPTER_CAPS* pCaps; WDF_OBJECT_ATTRIBUTES* ObjectAttributes; };
struct IDARG_OUT_ADAPTER_INIT { IDDCX_ADAPTER AdapterObject; };
struct IDARG_IN_ADAPTER_INIT_FINISHED { NTSTATUS AdapterInitStatus; };
struct IDARG_IN_MONITORCREATE { WDF_OBJECT_ATTRIBUTES* ObjectAttributes; IDDCX_MONITOR_INFO* pMonitorInfo; };
struct IDARG_OUT_MONITORCREATE { IDDCX_MONITOR MonitorObject; };
struct IDARG_OUT_MONITORARRIVAL { LUID OsAdapterLuid; UINT OsTargetId; };
struct IDARG_IN_PARSEMONITORDESCRIPTION { IDDCX_MONITOR_DESCRIPTION MonitorDescription; UINT MonitorModeBufferInputCount; IDDCX_MONITOR_MODE* pMonitorModes; };
struct IDARG_OUT_PARSEMONITORDESCRIPTION { UINT MonitorModeBufferOutputCount; UINT PreferredMonitorModeIdx; };
struct IDARG_IN_GETDEFAULTDESCRIPTIONMODES { UINT DefaultMonitorModeBufferInputCount; IDDCX_MONITOR_MODE* pDefaultMonitorModes; };
struct IDARG_OUT_GETDEFAULTDESCRIPTIONMODES { UINT DefaultMonitorModeBufferOutputCount; UINT PreferredMonitorModeIdx; };
struct IDARG_IN_QUERYTARGETMODES { IDDCX_MONITOR_DESCRIPTION MonitorDescription; UINT TargetModeBufferInputCount; IDDCX_TARGET_MODE* pTargetModes; };
struct IDARG_OUT_QUERYTARGETMODES { UINT TargetModeBufferOutputCount; };
struct IDARG_IN_COMMITMODES { UINT PathCount; IDDCX_PATH* pPaths; };
struct IDARG_IN_SETSWAPCHAIN { IDDCX_SWAPCHAIN hSwapChain; LUID RenderAdapterLuid; HANDLE hNextSurfaceAvailable; };
struct IDXGIResource;
struct IDARG_OUT_RELEASEANDACQUIREBUFFER { struct { IDXGIResource* pSurface; } MetaData; };
struct IDARG_IN_SWAPCHAINSETDEVICE { void* pDevice; };
typedef NTSTATUS EVT_IDD_CX_ADAPTER_INIT_FINISHED(IDDCX_ADAPTER, const IDARG_IN_ADAPTER_INIT_FINISHED*);
typedef NTSTATUS EVT_IDD_CX_ADAPTER_COMMIT_MODES(IDDCX_ADAPTER, const IDARG_IN_COMMITMODES*);
typedef NTSTATUS EVT_IDD_CX_PARSE_MONITOR_DESCRIPTION(const IDARG_IN_PARSEMONITORDESCRIPTION*, IDARG_OUT_PARSEMONITORDESCRIPTION*);
typedef NTSTATUS EVT_IDD_CX_MONITOR_GET_DEFAULT_DESCRIPTION_MODES(IDDCX_MONITOR, const IDARG_IN_GETDEFAULTDESCRIPTIONMODES*, IDARG_OUT_GETDEFAULTDESCRIPTIONMODES*);
typedef NTSTATUS EVT_IDD_CX_MONITOR_QUERY_TARGET_MODES(IDDCX_MONITOR, const IDARG_IN_QUERYTARGETMODES*, IDARG_OUT_QUERYTARGETMODES*);
typedef NTSTATUS EVT_IDD_CX_MONITOR_ASSIGN_SWAPCHAIN(IDDCX_MONITOR, const IDARG_IN_SETSWAPCHAIN*);
typedef NTSTATUS EVT_IDD_CX_MONITOR_UNASSIGN_SWAPCHAIN(IDDCX_MONITOR);
#if IDDCX_VERSION_MINOR >= 10
enum IDDCX_BITS_PER_COMPONENT_VALUES { IDDCX_BITS_PER_COMPONENT_NONE=0, IDDCX_BITS_PER_COMPONENT_6=1, IDDCX_BITS_PER_COMPONENT_8=2, IDDCX_BITS_PER_COMPONENT_10=4, IDDCX_BITS_PER_COMPONENT_12=8, IDDCX_BITS_PER_COMPONENT_14=0x10, IDDCX_BITS_PER_COMPONENT_16=0x20 };
struct IDDCX_WIRE_BITS_PER_COMPONENT { UINT Value; };
enum IDDCX_COLOR_SPACE { IDDCX_COLOR_SPACE_UNINITIALIZED=0, IDDCX_COLOR_SPACE_G22_P709=1, IDDCX_COLOR_SPACE_G2084_P2020=2, IDDCX_COLOR_SPACE_G22_P709_WCG=3 };
struct IDDCX_WIRE_FORMAT_INFO { IDDCX_COLOR_SPACE ColorSpace; IDDCX_WIRE_BITS_PER_COMPONENT BitsPerComponent; };
enum IDDCX_TARGET_CAPS { IDDCX_TARGET_CAPS_NONE=0, IDDCX_TARGET_CAPS_WIDE_COLOR_SPACE=1, IDDCX_TARGET_CAPS_HIGH_COLOR_SPACE=2 };
struct IDDCX_MONITOR_MODE2 { UINT Size; IDDCX_MONITOR_MODE_ORIGIN Origin; DISPLAYCONFIG_VIDEO_SIGNAL_INFO MonitorVideoSignalInfo; IDDCX_WIRE_BITS_PER_COMPONENT BitsPerComponent; };
struct IDDCX_TARGET_MODE2 { UINT Size; DISPLAYCONFIG_TARGET_MODE TargetVideoSignalInfo; UINT64 RequiredBandwidth; IDDCX_WIRE_BITS_PER_COMPONENT BitsPerComponent; };
struct IDDCX_PATH2 { UINT Size; IDDCX_MONITOR MonitorObject; UINT Flags; DISPLAYCONFIG_VIDEO_SIGNAL_INFO TargetVideoSignalInfo; IDDCX_WIRE_FORMAT_INFO WireFormatInfo; };
struct IDARG_IN_PARSEMONITORDESCRIPTION2 { IDDCX_MONITOR_DESCRIPTION MonitorDescription; UINT MonitorModeBufferInputCount; IDDCX_MONITOR_MODE2* pMonitorModes; };
struct IDARG_IN_QUERYTARGETMODES2 { IDDCX_MONITOR_DESCRIPTION MonitorDescription; UINT TargetModeBufferInputCount; IDDCX_TARGET_MODE2* pTargetModes; };
struct IDARG_IN_COMMITMODES2 { UINT PathCount; IDDCX_PATH2* pPaths; };
struct IDARG_IN_QUERYTARGET_INFO { UINT ConnectorIndex; };
struct IDARG_OUT_QUERYTARGET_INFO { IDDCX_TARGET_CAPS TargetCaps; IDDCX_WIRE_BITS_PER_COMPONENT DitheringSupport; };
enum IDDCX_DEFAULT_HDR_METADATA_TYPE { IDDCX_DEFAULT_HDR_METADATA_TYPE_HDR10 = 1 };
struct IDDCX_HDR10_METADATA { BYTE b[26]; };
struct IDARG_IN_MONITOR_SET_DEFAULT_HDR_METADATA { IDDCX_DEFAULT_HDR_METADATA_TYPE Type; UINT Size; union { IDDCX_HDR10_METADATA* pHdr10; } Data; };
typedef NTSTATUS EVT_IDD_CX_ADAPTER_QUERY_TARGET_INFO(IDDCX_ADAPTER, IDARG_IN_QUERYTARGET_INFO*, IDARG_OUT_QUERYTARGET_INFO*);
typedef NTSTATUS EVT_IDD_CX_PARSE_MONITOR_DESCRIPTION2(const IDARG_IN_PARSEMONITORDESCRIPTION2*, IDARG_OUT_PARSEMONITORDESCRIPTION*);
typedef NTSTATUS EVT_IDD_CX_MONITOR_QUERY_TARGET_MODES2(IDDCX_MONITOR, const IDARG_IN_QUERYTARGETMODES2*, IDARG_OUT_QUERYTARGETMODES*);
typedef NTSTATUS EVT_IDD_CX_ADAPTER_COMMIT_MODES2(IDDCX_ADAPTER, const IDARG_IN_COMMITMODES2*);
typedef NTSTATUS EVT_IDD_CX_MONITOR_SET_DEFAULT_HDR_METADATA(IDDCX_MONITOR, const IDARG_IN_MONITOR_SET_DEFAULT_HDR_METADATA*);
#endif
struct IDD_CX_CLIENT_CONFIG {
  UINT Size;
  EVT_IDD_CX_ADAPTER_INIT_FINISHED* EvtIddCxAdapterInitFinished;
  EVT_IDD_CX_ADAPTER_COMMIT_MODES* EvtIddCxAdapterCommitModes;
  EVT_IDD_CX_PARSE_MONITOR_DESCRIPTION* EvtIddCxParseMonitorDescription;
  EVT_IDD_CX_MONITOR_GET_DEFAULT_DESCRIPTION_MODES* EvtIddCxMonitorGetDefaultDescriptionModes;
  EVT_IDD_CX_MONITOR_QUERY_TARGET_MODES* EvtIddCxMonitorQueryTargetModes;
  EVT_IDD_CX_MONITOR_ASSIGN_SWAPCHAIN* EvtIddCxMonitorAssignSwapChain;
  EVT_IDD_CX_MONITOR_UNASSIGN_SWAPCHAIN* EvtIddCxMonitorUnassignSwapChain;
#if IDDCX_VERSION_MINOR >= 10
  EVT_IDD_CX_ADAPTER_QUERY_TARGET_INFO* EvtIddCxAdapterQueryTargetInfo;
  EVT_IDD_CX_PARSE_MONITOR_DESCRIPTION2* EvtIddCxParseMonitorDescription2;
  EVT_IDD_CX_MONITOR_QUERY_TARGET_MODES2* EvtIddCxMonitorQueryTargetModes2;
  EVT_IDD_CX_ADAPTER_COMMIT_MODES2* EvtIddCxAdapterCommitModes2;
  EVT_IDD_CX_MONITOR_SET_DEFAULT_HDR_METADATA* EvtIddCxMonitorSetDefaultHdrMetadata;
#endif
};
inline void IDD_CX_CLIENT_CONFIG_INIT(IDD_CX_CLIENT_CONFIG* c){ *c = IDD_CX_CLIENT_CONFIG{}; }
inline NTSTATUS IddCxDeviceInitConfig(PWDFDEVICE_INIT, const IDD_CX_CLIENT_CONFIG*){return 0;}
inline NTSTATUS IddCxDeviceInitialize(WDFDEVICE){return 0;}
inline NTSTATUS IddCxAdapterInitAsync(const IDARG_IN_ADAPTER_INIT*, IDARG_OUT_ADAPTER_INIT*){return 0;}
inline NTSTATUS IddCxMonitorCreate(IDDCX_ADAPTER, const IDARG_IN_MONITORCREATE*, IDARG_OUT_MONITORCREATE*){return 0;}
inline NTSTATUS IddCxMonitorArrival(IDDCX_MONITOR, IDARG_OUT_MONITORARRIVAL*){return 0;}
inline NTSTATUS IddCxMonitorDeparture(IDDCX_MONITOR){return 0;}
inline HRESULT IddCxSwapChainSetDevice(IDDCX_SWAPCHAIN, const IDARG_IN_SWAPCHAINSETDEVICE*){return 0;}
inline HRESULT IddCxSwapChainReleaseAndAcquireBuffer(IDDCX_SWAPCHAIN, IDARG_OUT_RELEASEANDACQUIREBUFFER*){return 0;}
#if IDDCX_VERSION_MINOR >= 4
inline HRESULT IddCxSwapChainFinishedProcessingFrame(IDDCX_SWAPCHAIN){return 0;}
#endif
// WdfObjectGet for IddCx handle types: emulate by overloads added per context type
#define NDSP_STUB_IDDCX_GET(T) \
  inline T* WdfObjectGet_##T(IDDCX_ADAPTER){ static thread_local char b[sizeof(T)]; return (T*)b; } \
  inline T* WdfObjectGet_##T(IDDCX_MONITOR){ static thread_local char b[sizeof(T)]; return (T*)b; }
